---
name: config-silverstripe-elemental-bootstrap-featuresection
After:
  - '#assets'
---
Silverstripe\Assets\File:
  # file_types:
  #   svg: 'Scalable Vector Graphic'
  allowed_extensions:
    - svg
